### ISSUE TITLE
Observations des Jupyter existants sur kaggle 

### ISSUE THREAD

**Issue by Rvanelven** [Rvanelven/steamator#16]
Trier ce qui peut être utile pour la data analyse des différents jupyter sur kaggle
Constituer un Jupyter qui nous aidera 
https://www.kaggle.com/nikdavis/steam-store-games/code

**Comment by NathanJolivetWeb** [comment]
J'ai clean le notebook EDA, ce serait intéressant que vous le lisiez pour avoir une vu globale de la donnée présente.
