### ISSUE TITLE
Analyse via NLP des descriptions

### ISSUE THREAD

**Issue by Rvanelven** [Rvanelven/steamator#24]
Colonnes short_desc et detailed_desc pourraient nous permettre de voir l'impact potentiellement de la description sur notre target
Création d'un modèle NLP avec un travail de preprocessing à faire sur les deux colonnes au dessus 
Issues à faire si on part dessus + tard

**Comment by NathanJolivetWeb** [comment]
- [x]  Analyse NLP des descriptions des jeux vidéos
- [x]  Commentaires du notebook en français
- [x]  Création d'une chaine de caractère contenant les 100 mots les plus fréquents
